### ISSUE TITLE
is 17.1.6 supported?

### ISSUE THREAD

**Issue by albertoVieiraNeto** [DevExpress/DevExtreme-Data-BreezeJS#10]
I'm developing an application using devextreme-angular v17.1.6 and I'm interested in the breeze datasource, is this wrapper compatible with the latest version of breeze?

**Comment by Seteh** [comment]
Hi @albertoVieiraNeto, thank you for interesting in our products. 
 
At the moment, the current implementation of `BreezeJS` data layer extension isn't working with version `17.1.6` of `DevExtreme`. But we are preparing a new patch, so it will available soon.

**Comment by Seteh** [comment]
@albertoVieiraNeto, we've updated the repro so from now, you're able to use `Breeze` data layer extension within `17.1.6` version of `DevExtreme`. 

Let us know if you encounter any problems and will publish the sample code for you as fast as possible.
