### ISSUE TITLE
Update to DevExtreme 16.1.5

### ISSUE THREAD

**Issue by GoshaFighten** [DevExpress/DevExtreme-Data-BreezeJS#3]

**Comment by stephanlotter** [comment]
I use DevExtreme and Breeze in an AngularJS app. It seems that in this case Breeze uses the Angular $q. $q does not implement the fail method, only catch.

**Comment by stephanlotter** [comment]
Your __isNumber = DX.require("/utils/utils.common").isNumber statement fails in my environment. I replaced it with lodash's _.isNumber.

**Comment by stephanlotter** [comment]
This library is not compatible with Breeze+Angular.

When using BreezeJS and Angular the promises returned from calls to Breeze do not implement the fail method, but rather the catch method.

In order for me to get this library to work in my project I had to replace all .fail calls with .catch calls in cases where entityManager calls were made.

In my Angular app I include the following breeze scripts (in order):
breeze.min.js
breeze.bridge.angular.js
breeze.directives.js

Read more here: http://breeze.github.io/doc-js/breeze-angular.html
